### ISSUE TITLE
the asc and desc icon is not correct?

### ISSUE THREAD

**Issue by IamTonyZHOU** [NonFactors/MVC5.Grid#32]
It should be
```CSS
.up_arrow:before         { content: "\2191"; }
.down_arrow:before       { content: "\2193"; }
```

But in css it is
```CSS
mvc-grid-sort.asc:after {
    content: "\2193";
}

.mvc-grid-sort.desc:after {
    content: "\2191";
}
```
